services:
  devcontainer:
    build:
      context: .devcontainer
      args:
        NODE_VERSION: ${NODE_VERSION}
        PYTHON_VERSION: ${PYTHON_VERSION}
    volumes:
      - .:/workspace:cached
    command: [ "sleep infinity" ]
  # frontend:
  #   build:
  #     context: frontend
  #     target: dev
  #   environment:
  #     - NEXT_TELEMETRY_DISABLED=1
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./frontend:/app
  #     - node_modules:/app/node_modules
  postgres:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  node_modules:
  postgres_data:
