services:
  devcontainer:
    build:
      context: .devcontainer
      args:
        NODE_VERSION: ${NODE_VERSION}
        PYTHON_VERSION: ${PYTHON_VERSION}
    volumes:
      - .:/workspace:cached
    command: [ "sleep infinity" ]
